// @ts-nocheck
import { Account, Transaction, Budget, RecurringTransaction } from '@/types/finance';
import { v4 as uuidv4 } from 'uuid';
import { subDays, subMonths, startOfMonth, addDays } from 'date-fns';

export const generateSampleData = () => {
  const now = new Date();
  
  // Sample Accounts
  const accounts: Account[] = [
    {
      id: uuidv4(),
      name: 'Main Checking',
      type: 'checking',
      balance: 5420.50,
      currency: 'GBP',
      color: '#3b82f6',
      createdAt: subMonths(now, 6).toISOString(),
      updatedAt: subMonths(now, 6).toISOString(),
      lowBalanceWarning: 1000, // Alert when below £1,000
      highBalanceWarning: 10000, // Alert when above £10,000
    },
    {
      id: uuidv4(),
      name: 'Emergency Savings',
      type: 'savings',
      balance: 15000.00,
      currency: 'GBP',
      color: '#10b981',
      createdAt: subMonths(now, 6).toISOString(),
      updatedAt: subMonths(now, 6).toISOString(),
      lowBalanceWarning: 10000, // Alert when below £10,000
      highBalanceWarning: 20000, // Alert when above £20,000
    },
    {
      id: uuidv4(),
      name: 'Chase Credit Card',
      type: 'credit',
      balance: -1250.75,
      currency: 'GBP',
      color: '#ef4444',
      createdAt: subMonths(now, 6).toISOString(),
      updatedAt: subMonths(now, 6).toISOString(),
      lowBalanceWarning: -2000, // Alert when below -£2,000 (more debt)
    },
    {
      id: uuidv4(),
      name: 'Investment Portfolio',
      type: 'investment',
      balance: 42500.00,
      currency: 'GBP',
      color: '#8b5cf6',
      createdAt: subMonths(now, 6).toISOString(),
      updatedAt: subMonths(now, 6).toISOString(),
      lowBalanceWarning: 40000, // Alert when below £40,000
    },
    {
      id: uuidv4(),
      name: 'Cash Wallet',
      type: 'cash',
      balance: 350.00,
      currency: 'GBP',
      color: '#f59e0b',
      createdAt: subMonths(now, 6).toISOString(),
      updatedAt: subMonths(now, 6).toISOString(),
      lowBalanceWarning: 100, // Alert when below £100
      highBalanceWarning: 500, // Alert when above £500
    },
  ];

  // Sample Transactions
  const transactions: Transaction[] = [
    // This month
    {
      id: uuidv4(),
      type: 'income',
      amount: 5000.00,
      category: 'salary',
      payee: 'Acme Corporation',
      description: 'Monthly Salary',
      date: startOfMonth(now).toISOString(),
      accountId: accounts[0].id,
      createdAt: startOfMonth(now).toISOString(),
      updatedAt: startOfMonth(now).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 1200.00,
      category: 'rent',
      payee: 'Landlord Property Management',
      description: 'Monthly Rent Payment',
      date: subDays(now, 2).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(now, 2).toISOString(),
      updatedAt: subDays(now, 2).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 85.50,
      category: 'groceries',
      payee: 'Whole Foods Market',
      description: 'Weekly grocery shopping',
      date: subDays(now, 3).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(now, 3).toISOString(),
      updatedAt: subDays(now, 3).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 45.00,
      category: 'dining',
      payee: 'Italian Restaurant',
      description: 'Dinner with friends',
      date: subDays(now, 5).toISOString(),
      accountId: accounts[2].id,
      createdAt: subDays(now, 5).toISOString(),
      updatedAt: subDays(now, 5).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 120.00,
      category: 'Utilities',
      payee: 'Electric Company',
      description: 'Electric Bill',
      date: subDays(now, 7).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(now, 7).toISOString(),
      updatedAt: subDays(now, 7).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 60.00,
      category: 'Transportation',
      payee: 'Shell Gas Station',
      description: 'Gas Station',
      date: subDays(now, 8).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(now, 8).toISOString(),
      updatedAt: subDays(now, 8).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 15.99,
      category: 'Subscriptions',
      payee: 'Netflix',
      description: 'Netflix Subscription',
      date: subDays(now, 10).toISOString(),
      accountId: accounts[2].id,
      createdAt: subDays(now, 10).toISOString(),
      updatedAt: subDays(now, 10).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 125.00,
      category: 'Shopping',
      payee: 'Nike Store',
      description: 'New Shoes',
      date: subDays(now, 12).toISOString(),
      accountId: accounts[2].id,
      createdAt: subDays(now, 12).toISOString(),
      updatedAt: subDays(now, 12).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'transfer',
      amount: 500.00,
      category: 'Transfer',
      description: 'Transfer to Savings',
      date: subDays(now, 14).toISOString(),
      accountId: accounts[0].id,
      toAccountId: accounts[1].id,
      createdAt: subDays(now, 14).toISOString(),
      updatedAt: subDays(now, 14).toISOString(),
    },
    // Last month
    {
      id: uuidv4(),
      type: 'income',
      amount: 5000.00,
      category: 'Salary',
      payee: 'Acme Corporation',
      description: 'Monthly Salary',
      date: startOfMonth(subMonths(now, 1)).toISOString(),
      accountId: accounts[0].id,
      createdAt: startOfMonth(subMonths(now, 1)).toISOString(),
      updatedAt: startOfMonth(subMonths(now, 1)).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'income',
      amount: 800.00,
      category: 'Freelance',
      payee: 'Design Client',
      description: 'Web Design Project',
      date: subDays(subMonths(now, 1), 10).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(subMonths(now, 1), 10).toISOString(),
      updatedAt: subDays(subMonths(now, 1), 10).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 1200.00,
      category: 'Rent',
      payee: 'Landlord Property Management',
      description: 'Monthly Rent Payment',
      date: subDays(subMonths(now, 1), 2).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(subMonths(now, 1), 2).toISOString(),
      updatedAt: subDays(subMonths(now, 1), 2).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 250.00,
      category: 'Groceries',
      payee: 'Tesco',
      description: 'Monthly Groceries',
      date: subDays(subMonths(now, 1), 5).toISOString(),
      accountId: accounts[0].id,
      createdAt: subDays(subMonths(now, 1), 5).toISOString(),
      updatedAt: subDays(subMonths(now, 1), 5).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'income',
      amount: 150.00,
      category: 'Investment Income',
      payee: 'Vanguard',
      description: 'Dividend Payment',
      date: subDays(subMonths(now, 1), 15).toISOString(),
      accountId: accounts[3].id,
      createdAt: subDays(subMonths(now, 1), 15).toISOString(),
      updatedAt: subDays(subMonths(now, 1), 15).toISOString(),
    },
  ];

  // Sample Budgets
  const budgets: Budget[] = [
    {
      id: uuidv4(),
      name: 'Groceries Budget',
      category: 'Groceries',
      amount: 400.00,
      period: 'monthly',
      alertThreshold: 80,
      createdAt: subMonths(now, 3).toISOString(),
    },
    {
      id: uuidv4(),
      name: 'Dining Out',
      category: 'Dining',
      amount: 200.00,
      period: 'monthly',
      alertThreshold: 75,
      createdAt: subMonths(now, 3).toISOString(),
    },
    {
      id: uuidv4(),
      name: 'Transportation',
      category: 'Transportation',
      amount: 300.00,
      period: 'monthly',
      alertThreshold: 85,
      createdAt: subMonths(now, 3).toISOString(),
    },
    {
      id: uuidv4(),
      name: 'Entertainment',
      category: 'Entertainment',
      amount: 150.00,
      period: 'monthly',
      alertThreshold: 80,
      createdAt: subMonths(now, 3).toISOString(),
    },
    {
      id: uuidv4(),
      name: 'Shopping',
      category: 'Shopping',
      amount: 300.00,
      period: 'monthly',
      alertThreshold: 90,
      createdAt: subMonths(now, 3).toISOString(),
    },
  ];

  // Sample Recurring Transactions
  const recurringTransactions: RecurringTransaction[] = [
    {
      id: uuidv4(),
      type: 'income',
      amount: 5000.00,
      category: 'salary',
      payee: 'Acme Corporation',
      description: 'Monthly Salary',
      frequency: 'monthly',
      startDate: subMonths(now, 6).toISOString(),
      nextDate: addDays(startOfMonth(now), 0).toISOString(), // 1st of month
      accountId: accounts[0].id,
      isActive: true,
      createdAt: subMonths(now, 6).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 1200.00,
      category: 'rent',
      payee: 'Landlord Property Management',
      description: 'Monthly Rent',
      frequency: 'monthly',
      startDate: subMonths(now, 6).toISOString(),
      nextDate: addDays(startOfMonth(now), 4).toISOString(), // 5th of month
      accountId: accounts[0].id,
      isActive: true,
      createdAt: subMonths(now, 6).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 15.99,
      category: 'subscriptions',
      payee: 'Netflix',
      description: 'Netflix Subscription',
      frequency: 'monthly',
      startDate: subMonths(now, 6).toISOString(),
      nextDate: addDays(startOfMonth(now), 14).toISOString(), // 15th of month
      accountId: accounts[2].id,
      isActive: true,
      createdAt: subMonths(now, 6).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 12.99,
      category: 'subscriptions',
      payee: 'Spotify',
      description: 'Spotify Premium',
      frequency: 'monthly',
      startDate: subMonths(now, 6).toISOString(),
      nextDate: addDays(startOfMonth(now), 19).toISOString(), // 20th of month
      accountId: accounts[2].id,
      isActive: true,
      createdAt: subMonths(now, 6).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'expense',
      amount: 120.00,
      category: 'utilities',
      payee: 'Electric Company',
      description: 'Electric Bill',
      frequency: 'monthly',
      startDate: subMonths(now, 6).toISOString(),
      nextDate: addDays(startOfMonth(now), 24).toISOString(), // 25th of month
      accountId: accounts[0].id,
      isActive: true,
      createdAt: subMonths(now, 6).toISOString(),
    },
    {
      id: uuidv4(),
      type: 'transfer',
      amount: 500.00,
      category: 'Transfer',
      description: 'Automatic Savings',
      frequency: 'monthly',
      startDate: subMonths(now, 6).toISOString(),
      accountId: accounts[0].id,
      toAccountId: accounts[1].id,
      isActive: true,
      createdAt: subMonths(now, 6).toISOString(),
    },
  ];

  return {
    accounts,
    transactions,
    budgets,
    recurringTransactions,
  };
};
